### ISSUE TITLE
Invalid behaviour while inserting text into 'Add sugar level' modal

### ISSUE THREAD

**Issue by Lisek8** [Lisek8/Projekt-Kompetencyjny#4]
![issue](https://user-images.githubusercontent.com/15330843/71780853-d82c4a00-2fc7-11ea-8cf3-83e9a1e393d2.png)

Input expected to accept only numbers

**Comment by AlanTheGodHimself** [comment]
no sry nie wiedzalem ze maja byc tylko liczby XD ale bendzie poprawione spoko ok?
